name: Ubuntu Static Analysis

on:
  push:
    branches: [main]

jobs:
  ubuntu-static-analysis:
    runs-on: ubuntu-latest
    name: Static Analysis - Clang-Tidy
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/ubuntu-build-steps
        with:
          cmake_workflow: workflow-test-clang-debug
          install_tools: clang-tidy
