name: Windows Build

on:
  push:
    branches: [main]

jobs:
  windows-build:
    runs-on: windows-latest
    strategy:
      fail-fast: true
      matrix:
        build_type: [debug, release]
        library_type: [shared]
        include:
          # Test static libraries only in release build to minimize CI time
          - build_type: release
            library_type: static
    name: Build - msvc - ${{ matrix.build_type }} - ${{ matrix.library_type }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      
      - name: Setup MSVC
        uses: microsoft/setup-msbuild@v2
      
      - name: Run CMake workflow
        run: |
          cmake --workflow --preset workflow-test-msvc-${{ matrix.build_type }} -DBUILD_SHARED_LIBS=${{ matrix.library_type == 'shared' && 'ON' || 'OFF' }}
        shell: pwsh
